name: Security

on:
  push:
    branches: [ "release*", $default-branch, develop, feature/get_wal_end, main, master ]
  pull_request:
    branches: [ "release*", $default-branch, develop, feature/get_wal_end, main, master ]
  schedule:
    # Randomized weekly schedule so runners don't get a load spike at the same time every week.
    - cron: '31 19 * * 1'
  workflow_dispatch:

jobs:
  security:
    uses: IncodeTechnologies/ci/.github/workflows/security.yml@basic
